ark:
  container_name: ark
  image: aigrid/ark
  environment:
    - SESSIONNAME=SecondLifeArk
    - SERVERMAP=Ragnarok
    - SERVERPASSWORD="" 
    - ADMINPASSWORD=allweneedislove
    - BACKUPONSTART=1
    - UPDATEONSTART=1
    - TZ=Europe/Paris
    - GID=1000
    - UID=1000
  volumes:
    - /docker/ark:/ark
  ports:
   - 7778:7778/udp
   - 7778:7778
   - 27015:27015/udp
   - 27015:27015
   - 32330:32330
